version: '3.9'
services:
  app:
    container_name: app-container
    image: app-image:latest
    environment:
      - APP_ENV=local
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8081:8081
    depends_on:
      - database

  database:
    container_name: app-database
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432