// Code generated by MockGen. DO NOT EDIT.
// Source: app/features/authentication/domain/usecase/registration/registration_usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	exception "crosscheck-golang/app/exception"
	param "crosscheck-golang/app/features/authentication/data/param"
	entity "crosscheck-golang/app/features/authentication/domain/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRegistrationUsecase is a mock of RegistrationUsecase interface.
type MockRegistrationUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockRegistrationUsecaseMockRecorder
}

// MockRegistrationUsecaseMockRecorder is the mock recorder for MockRegistrationUsecase.
type MockRegistrationUsecaseMockRecorder struct {
	mock *MockRegistrationUsecase
}

// NewMockRegistrationUsecase creates a new mock instance.
func NewMockRegistrationUsecase(ctrl *gomock.Controller) *MockRegistrationUsecase {
	mock := &MockRegistrationUsecase{ctrl: ctrl}
	mock.recorder = &MockRegistrationUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistrationUsecase) EXPECT() *MockRegistrationUsecaseMockRecorder {
	return m.recorder
}

// Call mocks base method.
func (m *MockRegistrationUsecase) Call(param param.RegistrationParam) (*entity.AuthEntity, *exception.Exception) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Call", param)
	ret0, _ := ret[0].(*entity.AuthEntity)
	ret1, _ := ret[1].(*exception.Exception)
	return ret0, ret1
}

// Call indicates an expected call of Call.
func (mr *MockRegistrationUsecaseMockRecorder) Call(param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Call", reflect.TypeOf((*MockRegistrationUsecase)(nil).Call), param)
}
