name: Crosscheck-CI
on:
  pull_request:
    branches:
      - master
jobs:
  lint: 
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Check go version
        run: go version
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
          golangci-lint version
      - name: Run lint
        run: golangci-lint run

  unit-test:
    name: Unit Test
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Install make
        run: |
          sudo apt-get -s upgrade | grep -P "\d\K upgraded"
          sudo apt-get install make
          make -version
      - name: Install ginkgo
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo
          ginkgo version
      - name: Run test
        run: make test-run

  build:
    name: Build
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.docker.USERNAME }}
          password: ${{ secrets.docker.TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: user/app:latest
