name: Crosscheck-CI
on:
  pull_request:
    branches:
      - master
jobs:
  lint: 
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Update dependecies
        run: sudo apt-get -s upgrade | grep -P "\d\K upgraded"
      - name: Check go version
        run: go version
      - name: Install make
        run: |
          sudo apt-get install make
          make -version
      - name: Install ginkgo
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo
          ginkgo version
      - name: Install golang-migrate
        run: |
          curl -s https://packagecloud.io/install/repositories/golang-migrate/migrate/script.deb.sh | sudo bash
          sudo apt-get update
          sudo apt-get install migrate
          migrate -version
      - name: Install mockgen
        run: |
          sudo apt-get update
          sudo apt-get -y install mockgen
          mockgen
          
