name: Crosscheck-CI
on:
  pull_request:
    branches:
      - master
jobs:
  lint: 
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Update dependecies
        run: sudo apt-get -s upgrade | grep -P "\d\K upgraded"
      - name: Check go version
        run: go version
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
          golangci-lint version
          
